name: FiscalizaGov - Notificar (DOU)

on:
  schedule:
    # 08:00 Brasília ≈ 11:00 UTC (ajuste se necessário)
    - cron: "0 11 * * 1-6"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Opcional:
          # FISCALIZAGOV_TERMS: "imposto,tribut,contribui,benefício,programa,decreto,portaria"
        run: |
          python notificar_fiscalizagov.py
